config/routes.rb
QuoiQuoi::Application.routes.draw do
  devise_for :admin, controller: { sessions: 'admin/sessions' }

  as :admin do
    get 'admin/edit' => 'devise/registrations#edit', as: 'edit_admin_account'
    put 'admin' => 'devise/registrations#update', as: 'admin_account'
  end

  namespace :admin do
    root to: 'home#index'
    resource :privacy_statement, controller: :privacy_statement
    resource :term_of_service, controller: :term_of_service

    resources :home
    resources :articles do
      resources :article_images
    end
    resources :images
    resources :instructions do
      resources :instruction_images
    end
    resources :instruction_images
    resources :article_images
    resources :article_types
    resources :product_tags do
      put 'sort', on: :collection
    end
    resources :products do
      member do
        put :visible
        patch :visible
      end

      resources :product_custom_items, shallow: true

      # This is one way to shallow nesting resource from http://weblog.jamisbuck.org/2007/2/5/nesting-resources
      # The article is written by Jamis on February 05, 2007 @ 01:00 PM
      # However newest Rails support the "shallow" keyword to make easier
      #resources :product_material_types, name_prefix: 'product_'
      resources :product_material_types, shallow: true do
        member do
          put :visible
          patch :visible

          put :collapsed
          patch :collapsed
        end
      end

      resources :product_addition_images, shallow: true

      resources :product_option_groups, shallow: true do
        resources :product_options, shallow: true
      end
    end

    #resources :product_material_types do
    #  member do
    #    put :visible
    #    patch :visible
    #
    #    put :collapsed
    #    patch :collapsed
    #  end
    #end

    resources :past_work_types do
      member do
        put :visible
        patch :visible
      end

      collection do
        put :sort
        patch :sort
      end

      resources :past_works, shallow: true do
        member do
          put :visible
          patch :visible
        end

        resources :past_work_addition_images, shallow: true
      end
    end

    resources :board
    resources :questions

    resources :product_types

    resources :registrations do
      member do
        get :canceled, action: :show
      end

      collection do
        get :canceled
      end
    end

    resources :registration_payments

    resources :courses do
      member do
        put :status
        patch :status
      end

      resources :registrations, shallow: true
      resources :course_addition_images, shallow: true
      resources :course_option_groups, shallow: true do
        resources :course_options, shallow: true
      end
    end

    resources :travel_information do
      resources :travel_photos
    end
    resources :travel_photos
    resources :areas

    resources :other_products do
      member do
        put :visible
        patch :visible
      end
    end
    resources :designers
    resources :rent_infos
    resources :rent_info_images
    resources :rent_intros
    resources :requirements
    resources :shipping_fees
    resource :about_us, controller: 'about_us'
    resources :introduce_image_slides do
      put 'sort', on: :collection
    end
    resources :introduce_youtubes do
      put 'sort', on: :collection
    end

    resource :requirement_intros

    resources :orders do
      member do
        get :check, action: :check_show
        get :archive, action: :show
        get :canceled, action: :show
      end
      collection do
        get :csv, action: :download_csv, defaults: { format: :csv }
        get :check
        get :accept
        get :closed
        get :archive
        get :deliver
        get :canceled
      end
    end

    resources :order_payments

    resources :order_remittances do
      member do
        get :check, action: :edit
      end

      collection do
        get :check
      end
    end

    resources :registration_remittances do
      member do
        get :check, action: :edit
      end

      collection do
        get :check
      end
    end

    resources :user_gift_remittances do
      member do
        get :check, action: :edit
      end

      collection do
        get :check
      end
    end

    resources :messages

    resources :custom_orders do
      member do
        get :discussing, action: :show
        get :canceled, action: :show
      end

      collection do
        get :discussing
        get :canceled
      end
    end

    resources :custom_order_options

    resource :remittances

    resources :payments do
      collection do
        get :check
      end

      member do
        put :uncheck
      end
    end

    resources :locales do
      resources :order_information
      resources :instructions
    end
    resources :order_information

    resources :tops do
      put 'sort', on: :collection
    end

    resources :slides do
      put 'sort', on: :collection
    end
    resources :slide_positions
    resources :broadcasts do
      put 'sort', on: :collection
    end

    resources :materials do
      member do
        put :visible
        patch :visible
      end
    end
    resources :material_types do
      member do
        put :visible
        patch :visible

        put :collapsed
        patch :collapsed

        put :all
        patch :all
      end

      resources :materials
    end

    resources :users do
      resources :messages

      member do
        get :info
      end
    end

    resources :gifts do
      member do
        put :visible
        patch :visible
      end
    end
    resources :user_gifts do
      member do
        get :check, action: :check_show
      end

      collection do
        get :check
      end
    end

    resource :system, controller: :system
  end
  ###### namespace admin end ######

  resources :products do
    collection do
      get 'tag(/:tag)', action: :index, as: :tag
    end
  end

  localized do

    # For handling payment
    get 'order_payment/:action(/:id)', controller: :order_payment, as: 'order_payment'
    post 'order_payment_callback/allpay_complete' => 'order_payment_callback#allpay_complete'

    get 'registration_payment/:action(/:id)', controller: :registration_payment, as: 'registration_payment'
    post 'registration_payment_callback/allpay_complete' => 'registration_payment_callback#allpay_complete'

    get 'user_gift_payment/:action(/:id)', controller: :user_gift_payment, as: 'user_gift_payment'
    post 'user_gift_payment_callback/allpay_complete' => 'user_gift_payment_callback#allpay_complete'

    # Special for paypal payment feedback
    get 'order_payment_callback/paypal' => 'order_payment_callback#paypal'
    get 'orders/:id/cancel?token=EC-\w+' => 'orders#cancel'

    get 'registration_payment_callback/paypal' => 'registration_payment_callback#paypal'
    get 'registrations/:id/cancel?token=EC-\w+' => 'registrations#cancel'

    get 'user_gift_payment_callback/paypal' => 'user_gift_callback#paypal'
    get 'user_gifts/:id/cancel?token=EC-\w+' => 'user_gifts#cancel'

    devise_for :users, controllers: {
        omniauth_callbacks: 'users/omniauth_callbacks'
    }

    get 'search' => 'search#index'

    root to: 'home#index'

    get 'rss' => 'rss#index'
    get 'cart' => 'cart#index'
    put 'cart' => 'cart#update'
    patch 'cart' => 'cart#update'
    get 'cart/checkout' => 'cart#checkout'
    post 'cart/payment' => 'cart#payment'
    get 'user/token/:token' => 'user#email_signin', as: 'email_signin'
    get 'user/email_confirmation' => 'user#email_confirmation'
    post 'user/email_authencate' => 'user#email_authencate', as: 'email_authencate'

    devise_scope :user do
      get 'user' => 'user#index'
      get 'user/edit' => 'user#edit', as: :edit_user
      get 'password' => 'user#password'
      put 'update_password' => 'user#update_password'
      patch 'update_password' => 'user#update_password'
      put 'user' => 'user#update'
      patch 'user' => 'user#update'
      get 'email' => 'user#email'
    end

    resource :home do
      get 'style1' => 'home#style1'
      get 'style2' => 'home#style2'
    end
    resources :news
    resources :courses do
      get 'calendar', on: :collection
      member do
        get 'month(/:month)', action: :show, constraints: {month: /\d{1,2}/}, as: 'month'
        get 'past', action: :show
      end
      collection do
        get 'calendar'
        get 'month(/:month)', action: :index, constraints: {month: /\d{1,2}/}, as: 'month'
        get 'past', action: :past_all
        get 'past(/:id)', action: :past_all, constraints: {id: /\d{4}-\d{1,2}/}, as: 'past'
      end
    end
    resources :reports
    resource :recruitments
    resource :about, controller: 'about'
    resource :rents
    resource :contacts
    resources :messages
    resources :gifts
    resources :user_gifts do
      member do
        post :send_email, action: :send_email

        get :close, action: :close_show
        put :close
        patch :close
        put :cancel
        post :cancel

        put :report_remittance
        post :report_remittance

        post :return
        put :delivery_report

        post action: :update
      end

      collection do
        post :payment
        get :payment
        post :search
        put :discount
      end
    end

    resources :orders do
      collection do
        get :close, action: :close_index
      end

      member do
        get :close, action: :close_show
        get :pay, action: :pay_show
        put :close
        patch :close
        put :cancel
        post :cancel

        put :report_remittance
        post :report_remittance

        post :return
        put :delivery_report

        post action: :update
      end
    end

    resources :order_products
    resources :registrations do
      collection do
        get :close, action: :close_index

app/helpers/admin/order_information_helper.rb
module Admin::OrderInformationHelper
end

app/views/admin/order_information/_order_information_body_rows.html.erb
<% @current_order_information.each do |order_information| %>
  <tr>
    <td class="col-sm-2">
      <%= simple_format(order_information.bag_type) %>
    </td>
    <td>
      <%= simple_format(order_information.reference) %>
    </td>
    <td class="col-sm-3">
      <%= simple_format(order_information.note) %>
    </td>
    <td class="text-right col-sm-2">
      <%= link_to '修改', edit_admin_locale_order_information_path(order_information.locale_id, order_information), class: 'btn' %>
      <%= link_to '刪除', admin_locale_order_information_path(order_information.locale_id, order_information), class: 'btn btn-danger', method: :delete %>
    </td>
  </tr>
<% end %>

app/views/admin/order_information/edit.html.erb
<div class="col-xs-12">
  <div class="page-header page-header-with-buttons">
    <h1 class="pull-left">
      <i class="icon-info"></i>
      <span>訂購須知管理 (<%= Locale.where(id: params[:locale_id]).first.name %>)</span>
    </h1>
    <div class="pull-right">
      <ul class="breadcrumb">
        <%= render_breadcrumbs tag: 'li', separator: ' <li class="separator"><i class="icon-angle-right"></i></li> ' %>
      </ul>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <div class="box bordered-box" style="margin-bottom:0;">
        <div class="box-header">
          <div class="title"><i class="icon-info"></i>&nbsp;訂購須知</div>
          <div class="actions">
            <a class="btn box-collapse btn-xs btn-link" href="#"><i></i></a>
          </div>
        </div>
        <div class="box-content">
          <%= form_for [:admin, @order_information], html: {class: 'form validate-form'} do |f| %>
            <table class="table table-striped">
              <thead>
              <tr>
                <th class="col-sm-2">
                  包包種類
                </th>
                <th>
                  價格參考
                </th>
                <th class="col-sm-3">
                  備註
                </th>
              </tr>
              </thead>
              <tbody>
              <% @current_order_information.each do |order_information| %>
                <% if @order_information.id == order_information.id %>
                  <tr>
                    <td class="col-sm-2">
                      <%= f.text_area :bag_type, class: 'autosize form-control input-block', data: {'rule-required' => true}, placeholder: '請輸入包包種類' %>
                    </td>
                    <td>
                      <%= f.text_area :reference, class: 'autosize form-control input-block', data: {'rule-required' => true}, placeholder: '請輸入價目參考' %>
                    </td>
                    <td class="col-sm-3">
                      <%= f.text_area :note, class: 'autosize form-control input-block', placeholder: '請輸入備註' %>
                    </td>
                    <td class="text-right col-sm-2">
                      <%= f.hidden_field :locale_id %>
                      <%= link_to '取消', admin_locale_order_information_index_path(params[:locale_id]), class: 'btn btn-default' %>
                      <%= f.button class: 'btn btn-primary', type: 'submit' do %>
                        <i class="icon-save"></i>
                        儲存
                      <% end %>
                    </td>
                  </tr>
                <% else %>
                  <tr>
                    <td class="col-sm-2">
                      <%= simple_format(order_information.bag_type) %>
                    </td>
                    <td>
                      <%= simple_format(order_information.reference) %>
                    </td>
                    <td class="col-sm-3">
                      <%= simple_format(order_information.note) %>
                    </td>
                    <td class="text-right col-sm-2">
                      <%= link_to '修改', edit_admin_locale_order_information_path(order_information.locale_id, order_information), class: 'btn' %>
                      <%= link_to '刪除', admin_locale_order_information_path(order_information.locale_id, order_information), class: 'btn btn-danger', method: :delete %>
                    </td>
                  </tr>
                <% end %>
              <% end %>
              </tbody>
            </table>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/order_information/index.html.erb
<div class="col-xs-12">
  <div class="page-header page-header-with-buttons">
    <h1 class="pull-left">
      <i class="icon-info"></i>
      <span>訂購須知管理 (<%= Locale.where(id: params[:locale_id]).first.name %>)</span>
    </h1>
    <div class="pull-right">
      <div class="btn-group">
        <%= link_to '新增條目', new_admin_locale_order_information_path, class: 'btn btn-info' %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <div class="box bordered-box" style="margin-bottom:0;">
        <div class="box-header">
          <div class="title"><i class="icon-info"></i>&nbsp;訂購須知</div>
          <div class="actions">
            <a class="btn box-collapse btn-xs btn-link" href="#"><i></i></a>
          </div>
        </div>
        <div class="box-content">
          <table class="table table-striped">
            <thead>
            <tr>
              <th class="col-sm-2">
                包包種類
              </th>
              <th>
                價格參考
              </th>
              <th class="col-sm-3">
                備註
              </th>
              <th class="col-sm-2"></th>
            </tr>
            </thead>
            <tbody>
            <%= render 'order_information_body_rows' %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/order_information/new.html.erb
<div class="col-xs-12">
  <div class="page-header page-header-with-buttons">
    <h1 class="pull-left">
      <i class="icon-info"></i>
      <span>訂購須知管理 (<%= Locale.where(id: params[:locale_id]).first.name %>)</span>
    </h1>
    <div class="pull-right">
      <ul class="breadcrumb">
        <%= render_breadcrumbs tag: 'li', separator: ' <li class="separator"><i class="icon-angle-right"></i></li> ' %>
      </ul>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <div class="box bordered-box" style="margin-bottom:0;">
        <div class="box-header">
          <div class="title"><i class="icon-info"></i>&nbsp;訂購須知</div>
          <div class="actions">
            <a class="btn box-collapse btn-xs btn-link" href="#"><i></i></a>
          </div>
        </div>
        <div class="box-content">
          <%= form_for @order_information, url: admin_order_information_index_path, html: {class: 'form validate-form'} do |f| %>
            <table class="table table-striped">
              <thead>
              <tr>
                <th class="col-sm-2">
                  包包種類
                </th>
                <th>
                  價格參考
                </th>
                <th class="col-sm-3">
                  備註
                </th>
              </tr>
              </thead>
              <tbody>
              <%= render 'order_information_body_rows' %>
              <tr>
                <td class="col-sm-2">
                  <%= f.text_area :bag_type, class: 'autosize form-control input-block', data: {'rule-required' => true}, placeholder: '請輸入包包種類' %>
                </td>
                <td>
                  <%= f.text_area :reference, class: 'autosize form-control input-block', data: {'rule-required' => true}, placeholder: '請輸入價目參考' %>
                </td>
                <td class="col-sm-3">
                  <%= f.text_area :note, class: 'autosize form-control input-block', placeholder: '請輸入備註' %>
                </td>
                <td class="text-right col-sm-2">
                  <%= f.hidden_field :locale_id %>
                  <%= link_to '取消', admin_locale_order_information_index_path(params[:locale_id]), class: 'btn btn-default' %>
                  <%= f.button class: 'btn btn-primary', type: 'submit' do %>
                    <i class="icon-save"></i>
                    儲存
                  <% end %>
                </td>
              </tr>
              </tbody>
            </table>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>