config/routes.rb
    get 'admin/edit' => 'devise/registrations#edit', as: 'edit_admin_account'
    put 'admin' => 'devise/registrations#update', as: 'admin_account'
  end

  namespace :admin do
    root to: 'home#index'
    resource :privacy_statement, controller: :privacy_statement
    resource :term_of_service, controller: :term_of_service

    resources :home
    resources :articles do
      resources :article_images
    end
    resources :images
    resources :instructions do
      resources :instruction_images
    end
    resources :instruction_images
    resources :article_images
    resources :article_types
    resources :product_tags do
      put 'sort', on: :collection
    end
    resources :products do
      member do
        put :visible
        patch :visible
      end

      resources :product_custom_items, shallow: true

      # This is one way to shallow nesting resource from http://weblog.jamisbuck.org/2007/2/5/nesting-resources
      # The article is written by Jamis on February 05, 2007 @ 01:00 PM
      # However newest Rails support the "shallow" keyword to make easier
      #resources :product_material_types, name_prefix: 'product_'
      resources :product_material_types, shallow: true do
        member do
          put :visible
          patch :visible

          put :collapsed
          patch :collapsed
        end
      end

      resources :product_addition_images, shallow: true

      resources :product_option_groups, shallow: true do
        resources :product_options, shallow: true
      end
    end

    #resources :product_material_types do
    #  member do
    #    put :visible
    #    patch :visible
    #
    #    put :collapsed
    #    patch :collapsed
    #  end
    #end

    resources :past_work_types do
      member do
        put :visible
        patch :visible
      end

      collection do
        put :sort
        patch :sort
      end

      resources :past_works, shallow: true do
        member do
          put :visible
          patch :visible
        end

        resources :past_work_addition_images, shallow: true
      end
    end

    resources :board
    resources :questions

    resources :product_types

    resources :registrations do
      member do
        get :canceled, action: :show
      end

      collection do
        get :canceled
      end
    end

    resources :registration_payments

    resources :courses do
      member do
        put :status
        patch :status
      end

      resources :registrations, shallow: true
      resources :course_addition_images, shallow: true
      resources :course_option_groups, shallow: true do
        resources :course_options, shallow: true
      end
    end

    resources :travel_information do
      resources :travel_photos
    end
    resources :travel_photos
    resources :areas

    resources :other_products do
      member do
        put :visible
        patch :visible
      end
    end
    resources :designers
    resources :rent_infos
    resources :rent_info_images
    resources :rent_intros
    resources :requirements
    resources :shipping_fees
    resource :about_us, controller: 'about_us'
    resources :introduce_image_slides do
      put 'sort', on: :collection
    end
    resources :introduce_youtubes do
      put 'sort', on: :collection
    end

    resource :requirement_intros

    resources :orders do
      member do
        get :check, action: :check_show
        get :archive, action: :show
        get :canceled, action: :show
      end
      collection do
        get :csv, action: :download_csv, defaults: { format: :csv }
        get :check
        get :accept
        get :closed
        get :archive
        get :deliver
        get :canceled
      end
    end

    resources :order_payments

    resources :order_remittances do
      member do
        get :check, action: :edit
      end

      collection do
        get :check
      end
    end

    resources :registration_remittances do
      member do
        get :check, action: :edit
      end

      collection do
        get :check
      end
    end

    resources :user_gift_remittances do
      member do
        get :check, action: :edit
      end

      collection do
        get :check
      end
    end

    resources :messages

    resources :custom_orders do
      member do
        get :discussing, action: :show
        get :canceled, action: :show
      end

      collection do
        get :discussing
        get :canceled
      end
    end

    resources :custom_order_options

    resource :remittances

    resources :payments do
      collection do
        get :check
      end

      member do
        put :uncheck
      end
    end

    resources :locales do
      resources :order_information
      resources :instructions
    end
    resources :order_information

    resources :tops do
      put 'sort', on: :collection
    end

    resources :slides do
      put 'sort', on: :collection
    end
    resources :slide_positions
    resources :broadcasts do
      put 'sort', on: :collection
    end

    resources :materials do
      member do
        put :visible
        patch :visible
      end
    end
    resources :material_types do
      member do
        put :visible
        patch :visible

        put :collapsed
        patch :collapsed

        put :all
        patch :all
      end

      resources :materials
    end

    resources :users do
      resources :messages

      member do
        get :info
      end
    end

    resources :gifts do
      member do
        put :visible
        patch :visible
      end
    end
    resources :user_gifts do
      member do
        get :check, action: :check_show
      end

      collection do
        get :check
      end
    end

    resource :system, controller: :system
  end
  ###### namespace admin end ######

  resources :products do
    collection do
      get 'tag(/:tag)', action: :index, as: :tag
    end
  end

  localized do

    # For handling payment
    get 'order_payment/:action(/:id)', controller: :order_payment, as: 'order_payment'
    post 'order_payment_callback/allpay_complete' => 'order_payment_callback#allpay_complete'

    get 'registration_payment/:action(/:id)', controller: :registration_payment, as: 'registration_payment'
    post 'registration_payment_callback/allpay_complete' => 'registration_payment_callback#allpay_complete'

    get 'user_gift_payment/:action(/:id)', controller: :user_gift_payment, as: 'user_gift_payment'
    post 'user_gift_payment_callback/allpay_complete' => 'user_gift_payment_callback#allpay_complete'

    # Special for paypal payment feedback
    get 'order_payment_callback/paypal' => 'order_payment_callback#paypal'
    get 'orders/:id/cancel?token=EC-\w+' => 'orders#cancel'

    get 'registration_payment_callback/paypal' => 'registration_payment_callback#paypal'
    get 'registrations/:id/cancel?token=EC-\w+' => 'registrations#cancel'

    get 'user_gift_payment_callback/paypal' => 'user_gift_callback#paypal'
    get 'user_gifts/:id/cancel?token=EC-\w+' => 'user_gifts#cancel'

    devise_for :users, controllers: {
        omniauth_callbacks: 'users/omniauth_callbacks'
    }

    get 'search' => 'search#index'

    root to: 'home#index'

    get 'rss' => 'rss#index'
    get 'cart' => 'cart#index'
    put 'cart' => 'cart#update'
    patch 'cart' => 'cart#update'
    get 'cart/checkout' => 'cart#checkout'
    post 'cart/payment' => 'cart#payment'
    get 'user/token/:token' => 'user#email_signin', as: 'email_signin'
    get 'user/email_confirmation' => 'user#email_confirmation'
    post 'user/email_authencate' => 'user#email_authencate', as: 'email_authencate'

    devise_scope :user do
      get 'user' => 'user#index'
      get 'user/edit' => 'user#edit', as: :edit_user
      get 'password' => 'user#password'
      put 'update_password' => 'user#update_password'
      patch 'update_password' => 'user#update_password'
      put 'user' => 'user#update'
      patch 'user' => 'user#update'
      get 'email' => 'user#email'
    end

    resource :home do
      get 'style1' => 'home#style1'
      get 'style2' => 'home#style2'
    end
    resources :news
    resources :courses do
      get 'calendar', on: :collection
      member do
        get 'month(/:month)', action: :show, constraints: {month: /\d{1,2}/}, as: 'month'
        get 'past', action: :show
      end
      collection do
        get 'calendar'
        get 'month(/:month)', action: :index, constraints: {month: /\d{1,2}/}, as: 'month'
        get 'past', action: :past_all
        get 'past(/:id)', action: :past_all, constraints: {id: /\d{4}-\d{1,2}/}, as: 'past'
      end
    end
    resources :reports
    resource :recruitments
    resource :about, controller: 'about'
    resource :rents
    resource :contacts
    resources :messages
    resources :gifts
    resources :user_gifts do
      member do
        post :send_email, action: :send_email

        get :close, action: :close_show
        put :close
        patch :close
        put :cancel
        post :cancel

        put :report_remittance
        post :report_remittance

        post :return
        put :delivery_report

        post action: :update
      end

      collection do
        post :payment
        get :payment
        post :search
        put :discount
      end
    end

    resources :orders do
      collection do
        get :close, action: :close_index
      end

      member do
        get :close, action: :close_show
        get :pay, action: :pay_show
        put :close
        patch :close
        put :cancel
        post :cancel

        put :report_remittance
        post :report_remittance

        post :return
        put :delivery_report

        post action: :update
      end
    end

    resources :order_products
    resources :registrations do
      collection do
        get :close, action: :close_index
        post :payment
        get :payment

        get :email
        post :verify
      end

      member do

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: {
      remittance: 0,
      paypal: 1,
      cvs_family: 2,
      cvs_ibon: 3,
      webatm: 4,
      atm: 5,
      alipay: 6,
      credit_card: 7,
      free: 8,
  }

  validates :user_id, presence: true

  belongs_to :user
  has_many :order_products, dependent: :delete_all

  accepts_nested_attributes_for :order_products

  belongs_to :locale

  belongs_to :shipping_fee

  has_many :order_custom_items
  accepts_nested_attributes_for :order_custom_items

  has_one :user_gift_serial

  has_one :order_payment, dependent: :destroy

  def paid?
    self.payment
  end

  def in_cart_empty?
    self.order_products.size <= 0 && self.order_custom_items.size <= 0
  end

  def self.in_cart(user_id)
    self.where(user_id: user_id, checkout: false).order(:created_at).last
  end

  def self.create_cart(user_id, locale_id)
    self.create({closed: false, user_id: user_id, checkout: false, locale_id: locale_id, currency: Locale.find(locale_id).currency})
  end

  def quantity
    self.order_products.count + self.order_custom_items.count
  end

  # Order.includes(:order_custom_items, :order_products).find(317).amount <======= For test
  def get_subtotal
    self.get_raw_subtotal + self.shipping_fee!
  end

  def get_ntd_subtotal
    locale = Locale.where(lang: 'zh-TW').first

    custom_items_subtotal = order_custom_items.map{ |item| (item.custom_order.locale_id != locale.id) ? (custom_order.price * 30) : custom_order.price  }.sum
    products_subtotal = self.order_products.map{|order_product| order_product.raw_price(locale.id) * order_product.quantity}.sum

    custom_items_subtotal + products_subtotal + self.shipping_fee!
  end

  def shipping_fee!
    shipping_fee = ShippingFeeTranslate.find_by_shipping_fee_id_and_locale_id(self.shipping_fee_id, self.locale_id)
    if shipping_fee.free_condition.blank? || self.get_raw_subtotal < shipping_fee.free_condition
      shipping_fee.fee
    else
      0
    end
  end

  def discount!
    discount = 0
    UserGiftSerial.where(order_id: self.id).each do |user_gift_serial|
      discount += user_gift_serial.user_gift.gift.gift_translates.where(locale_id: self.locale_id).first.quota
    end

    discount
  end

  def get_raw_subtotal
    (self.order_custom_items_subtotal + self.order_products_subtotal)
  end

  def order_custom_items_subtotal
    order_custom_items.map(&:custom_order).sum(&:price)
  end

  def order_products_subtotal
    self.order_products.map{|order_product| order_product.price * order_product.quantity}.sum
  end

  def has_expire_time?
    (self.remittance? || self.cvs_family? || self.cvs_ibon? || self.atm?) &&
        (!self.order_payment.expire_time.nil?)
  end

  def empty_expire_time?
    (self.remittance? || self.cvs_family? || self.cvs_ibon? || self.atm?) &&
        (self.order_payment.expire_time.nil?)
  end

  def remaining_time_to_archive
    ((((self.delivery_report_handled?)? self.delivery_report_handled_time : self.delivered_time) + 30.days - Time.zone.now) / 1.days).to_i
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/_cancel_search_condition.html.erb
<div class="box">
  <div class="box-header box-header-small">
    <div class="title">
      查詢條件
    </div>
    <div class="actions">
      <a class="btn box-collapse btn-xs btn-link" href="#"><i></i></a>
    </div>
  </div>
  <div class="box-content">
    <%= form_tag canceled_admin_orders_path, method: :get, html: {class: 'form'} do %>
      <div class="row">
        <div class="col-sm-4 col-xs-5">
          <span class="label label-default">取消時間</span>
          <div class="daterange">
            <div class="input-group">
              <%= text_field_tag('search_filter[cancel_time]',
                                 (!@search_filter.nil?)? @search_filter['cancel_time'] : '',
                                 class: 'form-control',
                                 placeholder: '所有時間') %>
              <span class="input-group-addon">
                    <i class='icon-time'></i>
              </span>
            </div>
          </div>
        </div>
        <div class="col-sm-3 col-xs-4 text-right pull-right">
          <div class="btn-toolbar">
            <button type="submit" class="btn btn-sm btn-inverse">
              <i class="icon-search"></i>
              查詢
            </button>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/orders/_deliver_search_condition.html.erb
<div class="box">
  <div class="box-header box-header-small">
    <div class="title">
      查詢條件
    </div>
    <div class="actions">
      <a class="btn box-collapse btn-xs btn-link" href="#"><i></i></a>
    </div>
  </div>
  <div class="box-content">
    <%= form_tag deliver_admin_orders_path, method: :get, html: {class: 'form'} do %>
      <div class="row">
        <div class="col-sm-3 col-xs-4 margin-bottom-10">
          <span class="label label-warning">等待出貨</span>
          <div class='switch switch-small' data-off-label='<i class="icon-remove"></i>' data-on-label='<i class="icon-ok"></i>' style="vertical-align: middle;">
            <%= check_box_tag 'search_filter[]', 'waiting', @search_filter.include?('waiting') %>
          </div>
        </div>

        <div class="col-sm-3 col-xs-4 margin-bottom-10">
          <span class="label label-success">已寄出</span>
          <div class='switch switch-small' data-off-label='<i class="icon-remove"></i>' data-on-label='<i class="icon-ok"></i>' style="vertical-align: middle;">
            <%= check_box_tag 'search_filter[]', 'delivered', @search_filter.include?('delivered') %>
          </div>
        </div>

        <div class="col-sm-3 col-xs-4 margin-bottom-10">
          <span class="label label-danger">寄出件有問題尚未解決</span>
          <div class='switch switch-small' data-off-label='<i class="icon-remove"></i>' data-on-label='<i class="icon-ok"></i>' style="vertical-align: middle;">
            <%= check_box_tag 'search_filter[]', 'problem', @search_filter.include?('problem') %>
          </div>
        </div>

        <div class="col-sm-3 col-xs-4 text-right pull-right">
          <div class="btn-toolbar">
            <button type="submit" class="btn btn-inverse">
              <i class="icon-search"></i>
              查詢
            </button>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/orders/_message_cancel.html.erb
<div class="alert alert-success alert-dismissable">
  <a class="close" data-dismiss="alert" href="#">×</a>
  <%= link_to(admin_order_path(flash[:id])) do %>
    訂單編號&nbsp;
    <%= flash[:id] %>
  <% end %>
  &nbsp;已經被您取消
</div>

app/views/admin/orders/_message_closed.html.erb
<div class="alert alert-success alert-dismissable">
  <a class="close" data-dismiss="alert" href="#">×</a>
  <%= link_to(admin_order_path(flash[:id])) do %>
    訂單編號&nbsp;
    <%= flash[:id] %>
  <% end %>
  &nbsp;已手動封存
</div>

app/views/admin/orders/_message_deleted.html.erb
<div class="alert alert-success alert-dismissable">
  <a class="close" data-dismiss="alert" href="#">×</a>
  <label class="text-muted">
    訂單編號&nbsp;
    <%= flash[:id] %>
  </label>
  &nbsp;已永久刪除
</div>

app/views/admin/orders/_message_delivered.html.erb
<div class="alert alert-success alert-dismissable">
  <a class="close" data-dismiss="alert" href="#">×</a>
  <%= link_to(edit_admin_order_path(flash[:id])) do %>
    訂單編號&nbsp;
    <%= flash[:id] %>
  <% end %>
  &nbsp;確認出貨, 系統已自動送信通知客戶
</div>

app/views/admin/orders/_order_detail.html.erb
<div class="box bordered-box sea-blue-border" style="margin-bottom:0;">
  <div class="box-header box-header-small">
    <div class="title">
      <strong>
        <%= link_to("訂單編號: #{order.id}", admin_order_path(order.id)) %>
      </strong>
    </div>
  </div>

  <% if order.order_custom_items.size > 0 %>
    <div class="box-content margin-bottom-10">
      <div class="responsive-table">
        <div class="scrollable-table">
          <table class="table table-striped" style="margin-bottom:0;">
            <thead>
            <tr>
              <th>
                訂製編號
              </th>
              <th>
                訂製費用
              </th>
              <th></th>
            </tr>
            </thead>
            <tbody>
            <% order.order_custom_items.each do |order_custom_item| %>
              <tr>
                <td>
                  <%= order_custom_item.custom_order.id %>
                </td>
                <td>
                  <%= number_to_currency(order_custom_item.custom_order.price) %>
                </td>
                <td class="text-right">
                  <%= link_to('詳細訂製內容', admin_custom_order_path(order_custom_item.custom_order.id), class: 'btn btn-default') %>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  <% end %>

  <% if order.order_products.size > 0 %>
    <div class="box-content box-no-padding">
      <div class="responsive-table">
        <div class="scrollable-table">
          <table class="data-table table table-striped" style="margin-bottom:0;">
            <thead>
            <tr>
              <th>
                商品編號
              </th>
              <th></th>
              <th>訂單項目</th>
              <th>小計</th>
              <th>
                <small class="label label-sm label-primary">
                  訂購數量
                </small>
                <small class="label label-sm label-warning">
                  剩餘數量
                </small>
              </th>
            </tr>
            </thead>
            <tbody>
            <% order.order_products.reject{|object| object.product.nil?}.each do |order_product| %>
              <% translate = ProductTranslate.where(product_id: order_product.product_id, locale_id: order.locale_id).first %>
              <tr>
                <td>
                  <%= link_to(
                          (order_product.product.product_type)?
                              edit_admin_other_product_path(order_product.product) : edit_admin_product_path(order_product.product)) do %>
                    <%= order_product.product_id %>
                    <span class="text-muted">
                    <i class="icon-info-sign"></i>
                  </span>
                  <% end %>
                </td>
                <td>
                  <%= image_tag order_product.product.image.url(:thumb), style: 'height:50px', alt: '' %>
                </td>
                <td>
                  <div>
                    <strong>
                      <%= truncate(order_product.product.product_translates.find_by_locale_id(Locale.find_by_lang('zh-TW').id).name, length: 14) %>
                    </strong>

                    <small class="text-muted">
                      <%= truncate(order_product.product.product_translates.find_by_locale_id(Locale.find_by_lang('en').id).name, length: 30) %>
                    </small>
                  </div>
                  <small class="text-muted">
                    所選項目
                  </small>
                  <% ProductOptionGroup.where(locale_id: order.locale_id, product_id: order_product.product_id).each do |group| %>
                    <div class="option-group">
                      <small><%= group.name %></small>
                      <div>
                        <% if group.product_options.where(id: order_product.order_product_options.map{|option| option.product_option_id}).size > 0 %>
                        <span class="label label-primary">
                          <%= group.product_options.where(id: order_product.order_product_options.map{|option| option.product_option_id}).first.content %>
                        </span>
                        <% else %>
                          <span class="label label-default"><i class="icon-warning-sign icon-fixed-width"></i>沒有所選項目</span>
                        <% end %>
                      </div>
                    </div>
                  <% end %>
                </td>
                <td>
                  <%= number_to_currency(order_product.price, locale: order.locale.lang) %>
                </td>
                <td>
                  <small class="label label-sm label-primary">
                    <%= order_product.quantity %>
                  </small>
                  <small class="label label-sm label-warning">
                    <%= translate.product.quantity %>
                  </small>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>

  <% end %>
</div>
<div class="row">
  <div class="col-sm-12">
    <h4 class="text-right">
      總金額 :
      <strong class="text-muted">
        <%= number_to_currency(order.get_subtotal, locale: order.locale.lang) %><br/>
        <small>運費: <%= number_to_currency(order.shipping_fee!, locale: order.locale.lang) %></small>
      </strong><br>
      <% if order.order_payment.completed? %>
        <small>
          付款完成日期 <%= order.order_payment.completed_time.strftime('%Y/%m/%d') %>
        </small>
      <% end %>
    </h4>
  </div>
</div>

app/views/admin/orders/_payment_info.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="box">
      <div class="box-header">
        <div class="title">
          付款資訊
        </div>
        <div class="actions">
          <a class="btn box-collapse btn-xs btn-link" href="#"><i></i></a>
        </div>
      </div>
      <div class="box-content">
        <% if @order.payment %>
          <div class="form-group">
            <label>付款方式</label>
            <div class="controls">
              <%= text_field_tag :wait, (@order.payment.wait?)? '匯款' : 'Paypal', class: 'form-control', disabled: 'disabled' %>
            </div>
          </div>
          <div class="form-group">
            <label>付款金額</label>
            <div class="controls">
              <%= text_field_tag :amount, (@order.payment.amount != 0)? number_to_currency(@order.payment.amount) : '尚未付款', class: 'form-control', disabled: 'disabled' %>
            </div>
          </div>
          <div class="form-group">
            <label>付款日期</label>
            <div class="controls">
              <%= text_field_tag :address, (@order.payment.pay_time)? @order.payment.pay_time.strftime('%Y/%m/%d') : '尚未付款', class: 'form-control', disabled: 'disabled' %>
            </div>
          </div>
        <% else %>
          <h4 class="text-center"><i class="icon-exclamation"></i>&nbsp;尚未選擇付款方式</h4>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/orders/archive.html.erb
<div class="col-xs-12">
  <div class="page-header page-header-with-buttons">
    <h1 class="pull-left">
      <i class="icon-ok"></i>
      <span>已封存訂單</span>
    </h1>
  </div>

  <%= render 'archive_search_condition' %>

  <div class="box bordered-box sea-blue-border" style="margin-bottom:0;">
    <div class="box-content box-no-padding">
      <div class="responsive-table">
        <div class="scrollable-table">
          <table class="data-table table table-striped" style="margin-bottom:0;">
            <thead>
            <tr>
              <th>訂單編號</th>
              <th>用戶id&nbsp;<label class="label label-success">點擊查看</label></th>
              <th>付款方式</th>
              <th>付款完成時間</th>
              <th>訂單寄出時間</th>
              <th>訂單封存時間</th>
              <th></th>
            </tr>
            </thead>
            <tbody>
            <% @orders.each do |order| %>
              <tr>
                <td>
                  <%= order.id %>
                </td>
                <td>
                  <%= link_to(info_admin_user_path(order.user_id),
                              data: {toggle: 'modal', target: '#user-detail'}
                      ) do %>
                    <%= order.user_id %>
                    <span class="text-muted">
                          <i class="icon-info-sign"></i>
                        </span>
                  <% end %>
                </td>
                <td>
                  <span class="label label-default"><%= t("#{order.payment_method}") %></span>
                </td>
                <td>
                  <%= order.order_payment.completed_time.strftime('%Y/%m/%d %H:%M') %>
                </td>
                <td>
                  <%= order.delivered_time.strftime('%Y/%m/%d %H:%M') %>
                </td>
                <td>
                  <%= order.closed_time.strftime('%Y/%m/%d %H:%M') %>
                </td>
                <td class="text-right">
                  <%= link_to(archive_admin_order_path(order), class: 'btn btn-md') do %>
                    <i class="icon-info icon-fixed-width"></i>
                  <% end %>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="modal fade reload-modal" id="user-detail"></div><!-- /.modal -->

app/views/admin/orders/index.erb
<div class="col-xs-12">
  <div class="page-header page-header-with-buttons">
    <h1 class="pull-left">
      <i class="icon-flag"></i>
      <span>訂單紀錄</span>
    </h1>
  </div>

  <% if !flash[:status].nil? %>
    <% if flash[:status][:cancel] == 'true' %>
      <%= render 'message_cancel' %>
    <% end %>
  <% elsif !flash[:id].nil? %>
    <%= render 'message_deleted' %>
  <% end %>

  <%= render 'search_condition' %>

  <div class="box bordered-box" style="margin-bottom:0;">
    <div class="box-content box-no-padding">
      <div class="responsive-table">
        <div class="scrollable-table">
          <div style="text-align: right">
            <a href="/admin/orders/csv" class="btn btn-success" id="download-csv">
              下載訂單
            </a>
          </div>
          <table class="data-table table table-striped" style="margin-bottom:0;">
            <thead>
            <tr>
              <th>訂單編號</th>
              <th>用戶id&nbsp;<label class="label label-success">點擊查看</label></th>
              <th>聯絡人</th>
              <th>訂單狀態</th>
              <th>出貨狀態</th>
              <th></th>
            </tr>
            </thead>
            <tbody>
            <% @orders.each do |order| %>
              <tr>
                <td>
                  <%= order.id %>
                </td>
                <td>
                  <%= link_to(info_admin_user_path(order.user_id),
                              data: {toggle: 'modal', target: '#user-detail'}
                      ) do %>
                    <%= order.user_id %>
                    <span class="text-muted">
                          <i class="icon-info-sign"></i>
                        </span>
                  <% end %>
                </td>
                <td>
                  <%= order.name %>
                </td>
                <td>
                  <% if order.order_payment.completed.nil? %>
                    <span class="label label-warning">等待付款</span>
                    <div>
                      <small>
                        使用&nbsp;<%= t("#{order.payment_method}") %>&nbsp;付款
                        <span class="text-muted">
                          <%= order.checkout_time.strftime('%Y/%m/%d %H:%I:%S') %> 結帳
                        </span>
                      </small>
                    </div>
                  <% elsif order.order_payment.completed? %>
                    <span class="label label-success">付款完成</span>
                    <div>
                      <small>使用&nbsp;<%= t("#{order.payment_method}") %>&nbsp;付款 (<%= order.order_payment.completed_time.strftime('%Y/%m/%d %H:%I:%S') %>)</small>
                    </div>
                  <% else %>
                    <span class="label label-danger">匯款有誤</span>
                    <small class="text-muted">
                      <%= order.checkout_time.strftime('%Y/%m/%d %H:%I:%S') %> 結帳
                    </small>
                  <% end %>
                </td>
                <td>
                  <%= render 'delivery_status', is_show_full: false, order: order if order.order_payment.completed? %>
                </td>
                <td class="text-right">
                  <%= link_to_if(order.order_payment.cancel?, '已取消', '#', class: 'btn btn-default disabled') do %>
                    <%= link_to_unless(order.order_payment.completed?, '取消訂單',
                                admin_order_payment_path(order.order_payment),
                                class: 'btn btn-default', data: {toggle: 'modal', target: '#cancel-dialog'}
                        ) {} %>
                  <% end %>
                  <%= link_to_unless(order.order_payment.completed?, content_tag(:i, '', class: 'icon-trash'), admin_order_path(order),
                              class: "btn btn-danger #{'disabled' unless order.order_payment.cancel?}",
                              data: {confirm: '永久刪除無法回復動作，確定要繼續嗎？'}, method: :delete) {} %>
                  <%= link_to(admin_order_path(order), class: 'btn btn-md') do %>
                    <i class="icon-info icon-fixed-width"></i>
                  <% end %>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="modal fade reload-modal" id="user-detail"></div><!-- /.modal -->
<div class="modal fade" id="cancel-dialog"></div><!-- /.modal -->

<script>

document.getElementById('download-csv').addEventListener('click', (event) => {
  event.preventDefault();

  const { target: { href } } = event;
  const { search } = window.location;
  
  window.open(`${href}${search}`, '_blank');
});

</script>