config/routes.rb
QuoiQuoi::Application.routes.draw do
  devise_for :admin, controller: { sessions: 'admin/sessions' }

  as :admin do
    get 'admin/edit' => 'devise/registrations#edit', as: 'edit_admin_account'
    put 'admin' => 'devise/registrations#update', as: 'admin_account'
  end

  namespace :admin do
    root to: 'home#index'
    resource :privacy_statement, controller: :privacy_statement
    resource :term_of_service, controller: :term_of_service

    resources :home
    resources :articles do
      resources :article_images
    end
    resources :images
    resources :instructions do
      resources :instruction_images
    end
    resources :instruction_images
    resources :article_images
    resources :article_types
    resources :product_tags do
      put 'sort', on: :collection
    end
    resources :products do
      member do
        put :visible
        patch :visible
      end

      resources :product_custom_items, shallow: true

      # This is one way to shallow nesting resource from http://weblog.jamisbuck.org/2007/2/5/nesting-resources
      # The article is written by Jamis on February 05, 2007 @ 01:00 PM
      # However newest Rails support the "shallow" keyword to make easier
      #resources :product_material_types, name_prefix: 'product_'
      resources :product_material_types, shallow: true do
        member do
          put :visible
          patch :visible

          put :collapsed
          patch :collapsed
        end
      end

      resources :product_addition_images, shallow: true

      resources :product_option_groups, shallow: true do
        resources :product_options, shallow: true
      end
    end

    #resources :product_material_types do
    #  member do
    #    put :visible
    #    patch :visible
    #
    #    put :collapsed
    #    patch :collapsed
    #  end
    #end

    resources :past_work_types do
      member do
        put :visible
        patch :visible
      end

      collection do
        put :sort
        patch :sort
      end

      resources :past_works, shallow: true do
        member do
          put :visible
          patch :visible
        end

        resources :past_work_addition_images, shallow: true
      end
    end

    resources :board
    resources :questions

    resources :product_types

    resources :registrations do
      member do
        get :canceled, action: :show
      end

      collection do
        get :canceled
      end
    end

    resources :registration_payments

    resources :courses do
      member do
        put :status
        patch :status
      end

      resources :registrations, shallow: true
      resources :course_addition_images, shallow: true
      resources :course_option_groups, shallow: true do
        resources :course_options, shallow: true
      end
    end

    resources :travel_information do
      resources :travel_photos
    end
    resources :travel_photos
    resources :areas

    resources :other_products do
      member do
        put :visible
        patch :visible
      end
    end
    resources :designers
    resources :rent_infos
    resources :rent_info_images
    resources :rent_intros
    resources :requirements
    resources :shipping_fees
    resource :about_us, controller: 'about_us'
    resources :introduce_image_slides do
      put 'sort', on: :collection
    end
    resources :introduce_youtubes do
      put 'sort', on: :collection
    end

    resource :requirement_intros

    resources :orders do
      member do
        get :check, action: :check_show
        get :archive, action: :show
        get :canceled, action: :show
      end
      collection do
        get :csv, action: :download_csv, defaults: { format: :csv }
        get :check
        get :accept
        get :closed
        get :archive
        get :deliver
        get :canceled
      end
    end

    resources :order_payments

    resources :order_remittances do
      member do
        get :check, action: :edit
      end

      collection do
        get :check
      end
    end

    resources :registration_remittances do
      member do
        get :check, action: :edit
      end

      collection do
        get :check
      end
    end

    resources :user_gift_remittances do
      member do
        get :check, action: :edit
      end

      collection do
        get :check
      end
    end

    resources :messages

    resources :custom_orders do
      member do
        get :discussing, action: :show
        get :canceled, action: :show
      end

      collection do
        get :discussing
        get :canceled
      end
    end

    resources :custom_order_options

    resource :remittances

    resources :payments do
      collection do
        get :check
      end

      member do
        put :uncheck
      end
    end

    resources :locales do
      resources :order_information
      resources :instructions
    end
    resources :order_information

    resources :tops do
      put 'sort', on: :collection
    end

    resources :slides do
      put 'sort', on: :collection
    end
    resources :slide_positions
    resources :broadcasts do
      put 'sort', on: :collection
    end

    resources :materials do
      member do
        put :visible
        patch :visible
      end
    end
    resources :material_types do
      member do
        put :visible
        patch :visible

        put :collapsed
        patch :collapsed

        put :all
        patch :all
      end

      resources :materials
    end

    resources :users do
      resources :messages

      member do
        get :info
      end
    end

    resources :gifts do
      member do
        put :visible
        patch :visible
      end
    end
    resources :user_gifts do
      member do
        get :check, action: :check_show
      end

      collection do
        get :check
      end
    end

    resource :system, controller: :system
  end
  ###### namespace admin end ######

  resources :products do
    collection do
      get 'tag(/:tag)', action: :index, as: :tag
    end
  end

  localized do

    # For handling payment
    get 'order_payment/:action(/:id)', controller: :order_payment, as: 'order_payment'
    post 'order_payment_callback/allpay_complete' => 'order_payment_callback#allpay_complete'

    get 'registration_payment/:action(/:id)', controller: :registration_payment, as: 'registration_payment'
    post 'registration_payment_callback/allpay_complete' => 'registration_payment_callback#allpay_complete'

    get 'user_gift_payment/:action(/:id)', controller: :user_gift_payment, as: 'user_gift_payment'
    post 'user_gift_payment_callback/allpay_complete' => 'user_gift_payment_callback#allpay_complete'

    # Special for paypal payment feedback
    get 'order_payment_callback/paypal' => 'order_payment_callback#paypal'
    get 'orders/:id/cancel?token=EC-\w+' => 'orders#cancel'

    get 'registration_payment_callback/paypal' => 'registration_payment_callback#paypal'
    get 'registrations/:id/cancel?token=EC-\w+' => 'registrations#cancel'

    get 'user_gift_payment_callback/paypal' => 'user_gift_callback#paypal'
    get 'user_gifts/:id/cancel?token=EC-\w+' => 'user_gifts#cancel'

    devise_for :users, controllers: {
        omniauth_callbacks: 'users/omniauth_callbacks'
    }

    get 'search' => 'search#index'

    root to: 'home#index'

    get 'rss' => 'rss#index'
    get 'cart' => 'cart#index'
    put 'cart' => 'cart#update'
    patch 'cart' => 'cart#update'
    get 'cart/checkout' => 'cart#checkout'
    post 'cart/payment' => 'cart#payment'
    get 'user/token/:token' => 'user#email_signin', as: 'email_signin'
    get 'user/email_confirmation' => 'user#email_confirmation'
    post 'user/email_authencate' => 'user#email_authencate', as: 'email_authencate'

    devise_scope :user do
      get 'user' => 'user#index'
      get 'user/edit' => 'user#edit', as: :edit_user
      get 'password' => 'user#password'
      put 'update_password' => 'user#update_password'
      patch 'update_password' => 'user#update_password'
      put 'user' => 'user#update'
      patch 'user' => 'user#update'
      get 'email' => 'user#email'
    end

    resource :home do
      get 'style1' => 'home#style1'
      get 'style2' => 'home#style2'
    end
    resources :news
    resources :courses do
      get 'calendar', on: :collection
      member do
        get 'month(/:month)', action: :show, constraints: {month: /\d{1,2}/}, as: 'month'
        get 'past', action: :show
      end
      collection do
        get 'calendar'
        get 'month(/:month)', action: :index, constraints: {month: /\d{1,2}/}, as: 'month'
        get 'past', action: :past_all
        get 'past(/:id)', action: :past_all, constraints: {id: /\d{4}-\d{1,2}/}, as: 'past'
      end
    end
    resources :reports
    resource :recruitments
    resource :about, controller: 'about'
    resource :rents
    resource :contacts
    resources :messages
    resources :gifts
    resources :user_gifts do
      member do
        post :send_email, action: :send_email

        get :close, action: :close_show
        put :close
        patch :close
        put :cancel
        post :cancel

        put :report_remittance
        post :report_remittance

        post :return
        put :delivery_report

        post action: :update
      end

      collection do
        post :payment
        get :payment
        post :search
        put :discount
      end
    end

    resources :orders do
      collection do
        get :close, action: :close_index
      end

      member do
        get :close, action: :close_show
        get :pay, action: :pay_show
        put :close
        patch :close
        put :cancel
        post :cancel

        put :report_remittance
        post :report_remittance

        post :return
        put :delivery_report

        post action: :update
      end
    end

    resources :order_products
    resources :registrations do
      collection do
        get :close, action: :close_index

app/controllers/admin/material_types_controller.rb
class Admin::MaterialTypesController < AdminController
  authorize_resource :material
  before_action :set_material_type, only: [:edit, :update, :visible, :collapsed, :all, :destroy]
  before_action :set_material_types, only: [:index, :edit]

  def index
  end

  def new
    @material_type = MaterialType.new

    Locale.all.order(:id).each do |locale|
      @material_type.material_type_translates.build(locale_id: locale.id)
    end
  end

  def edit
    render :new
  end

  def create
    @material_type = MaterialType.new(material_type_params)

    if @material_type.save
      redirect_to admin_material_types_path
    else
      render json: @material_type.errors
    end
  end

  def update
    if @material_type.update_attributes(material_type_params)
      redirect_to action: :index
    else
      render json: @material_type.errors
    end
  end

  def visible
    if @material_type.update_attribute(:visible, params[:visible])
      redirect_to action: :index
    else
      render json: @material_type.errors
    end
  end

  def collapsed
    if @material_type.update_attribute(:collapsed, params[:collapsed])
      redirect_to action: :index
    else
      render json: @material_type.errors
    end
  end

  def all
    if @material_type.update_attribute(:all, params[:all])
      redirect_to :back
    else
      render json: @material_type.errors
    end
  end

  def destroy
    if @material_type.destroy
      redirect_to action: :index
    else
      render json: @material_type.errors
    end
  end

  private
  def set_material_type
    @material_type = MaterialType.find(params[:id])
  end

  def set_material_types
    @material_types = MaterialType.all.order(:id)
  end

  def material_type_params
    params.require(:material_type).permit(:id, material_type_translates_attributes: [:id, :name, :locale_id])
  end
end

app/controllers/material_types_controller.rb
class MaterialTypesController < ApplicationController
  before_action :setup_navigation_content

  def show
    add_breadcrumb t('home'), home_path
    add_breadcrumb '精選訂製布料'

    params[:id] ||= MaterialType.limit(1).pluck(:id)
    @materials = Material.includes(:material_translate).where(material_translates: {
                                                                  locale_id: session[:locale_id]
                                                              }, material_type_id: params[:id])

    @website_title = "#{@material_types.find(params[:id]).material_type_translate.name} | #{@website_title}"
    @meta_og_title = @material_types.find(params[:id]).material_type_translate.name
    @meta_og_description = @material_types.find(params[:id]).material_type_translate.name
  end

  private
  def setup_navigation_content
    @material_types = MaterialType.includes(:material_type_translate).where(material_type_translates: {locale_id: session[:locale_id]}, visible: true)
  end
end

app/helpers/admin/material_types_helper.rb
module Admin::MaterialTypesHelper
end

app/helpers/material_types_helper.rb
module MaterialTypesHelper
end

app/views/admin/material_types/index.html.erb
<div class="col-xs-12">
  <div class="page-header page-header-with-buttons">
    <h1 class="pull-left">
      <i class="icon-tag"></i>
      <span>布料管理</span>
    </h1>
    <div class="pull-right">
      <div class="btn-group">
        <%= link_to '新增布料類別', new_admin_material_type_path, class: 'btn btn-info' %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <div class="box bordered-box" style="margin-bottom:0;">
        <div class="box-header">
          <div class="title">
            布料類別名稱列表
          </div>
          <div class="actions">
            <a class="btn box-remove btn-xs btn-link" href="#"><i class="icon-remove"></i></a>
            <a class="btn box-collapse btn-xs btn-link" href="#"><i></i></a>
          </div>
        </div>
        <div class="box-content">
          <table class="table table-striped data-table">
            <thead>
            <tr>
              <th>
                編號
              </th>
              <th>
                名稱
              </th>
              <th>

              </th>
            </tr>
            </thead>
            <tbody>
            <% @material_types.each do |material_type| %>
            <tr>
              <td>
                <%= material_type.id %>
              </td>
              <td>
                <% material_type.material_type_translates.order(:locale_id).reject{|translate| translate.name.blank?}.each_with_index do |translate, index| %>
                  <span class="label label-default"><%= translate.locale.name %></span>
                  <%= translate.name %>
                  <%= '<br/>'.html_safe if index != material_type.material_type_translates.length - 1 %>
                <% end %>
              </td>
              <td class="text-right">

                <%= link_to '查看此類別下的布料', admin_material_type_materials_path(material_type), class: 'btn btn-default' %>
                <%= link_to edit_admin_material_type_path(material_type), class: 'btn btn-default' do %>
                  <i class="icon-pencil"></i>
                <% end %>

                <% if material_type.visible? %>
                  <%= link_to(visible_admin_material_type_path(material_type, visible: false), class: 'btn btn-info btn-md', method: :put) do %>
                    <i class="icon-level-down"></i>
                  <% end %>
                <% else %>
                  <%= link_to(visible_admin_material_type_path(material_type, visible: true), class: 'btn btn-primary btn-md', method: :put) do %>
                    <i class="icon-level-up"></i>
                  <% end %>
                <% end %>

                <%= link_to admin_material_type_path(material_type), class: 'btn btn-danger', data: {confirm: '確定要刪除這個類別嗎?'}, method: :delete do %>
                  <i class="icon-remove"></i>
                <% end %>
              </td>
            </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/material_types/new.html.erb
<div class="col-xs-12">
  <div class="page-header page-header-with-buttons">
    <h1 class="pull-left">
      <i class="icon-tag"></i>
      <span>布料類別管理</span>
    </h1>
  </div>
  <div class="row">
    <div class="col-sm-6">
      <div class="box bordered-box" style="margin-bottom:0;">
        <div class="box-header">
          <div class="title"><i class="icon-tag"></i>&nbsp;管理布料類別</div>
          <div class="actions">
            <a class="btn box-collapse btn-xs btn-link" href="#"><i></i></a>
          </div>
        </div>
        <div class="box-content">
          <%= form_for [:admin, @material_type], html: {class: 'form validated-form'} do |form| %>
            <%= form.fields_for :material_type_translates do |field| %>
              <div class="form-group">
                <%= field.label :name, "類別名稱(#{field.object.locale.name})" %>
                <div class="controls">
                  <%= field.text_field :name, class: 'form-control', data: {'rule-required' => true} %>
                </div>
                <%= field.hidden_field :locale_id %>
              </div>
            <% end %>
            <div class="form-actions form-actions-padding text-right">
              <%= link_to '取消', admin_material_types_path, class: 'btn btn-default' %>
              <button type="submit" class="btn btn-primary">
                <i class="icon-save"></i>
                儲存
              </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>